[workspace]
members = [
    "aead",
    "cipher",
    "crypto-common",
    "digest",
    "password-hash",
    "signature",
    "signature/async",
    "universal-hash",
]

[patch.crates-io]
inout = { git = "https://github.com/RustCrypto/utils", branch = "add_inout" }
